// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using arrearsApi5_0.Data;

namespace arrearsApi5_0.Migrations{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221219114429_InitialMigration")]
    partial class InitialMigration{
        protected override void BuildTargetModel(ModelBuilder modelBuilder){
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");
#pragma warning restore 612, 618
        }
    }
}
